Rewards campaigns: Added emergency cancel campaign and add/remove set reward origin extrinsics
bit-country/Metaverse-Network pull request #239
Opened 2022-10-04 12:39 UTC by chexware

2022-10-05 21:20 UTC, justinphamnz requested changes
Please ensure safe check

2022-10-05 21:20 UTC, justinphamnz commented on pallets/reward/src/lib.rs
> +						campaign.cap = RewardType::FungibleTokens(c, b - amount);
This needs to be checked sub or saturating sub to ensure no overhead

2022-10-05 21:20 UTC, justinphamnz commented on pallets/reward/src/lib.rs
> +						let unclaimed_balance = r - b;
All calculation please use saturating

2022-10-05 23:09 UTC, chexware commented
@justinphamnz  I've updated the subtraction to saturting_sub

2022-10-06 00:24 UTC, justinphamnz approved these changes
Thanks @chexware. Great work.

2022-10-06 00:24 UTC, merged